/**
 * Converts The Radio Bench (MIT, github.com/jemcik/the-radio-bench) content
 * into typed SPECTRA Academy data:
 *   src/academy/course/course.gen.ts   — 25 chapters: blocks, labs, quizzes
 *   src/academy/course/glossary.gen.ts — ~283 glossary entries
 *
 * Run: npm run course:gen   (requires vendor/the-radio-bench — see README)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { createRequire } from 'node:module';
import { parseInline } from '../src/academy/course/inline.ts';

const require = createRequire(import.meta.url);

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SRC = `${ROOT}/vendor/the-radio-bench/src`;

const ui = JSON.parse(readFileSync(`${SRC}/i18n/locales/en/ui.json`, 'utf8'));

/* ------------------------------------------------------------------ */
/* Glossary: transpile the TS module and eval it to get the object.   */
/* ------------------------------------------------------------------ */

const glossTs = readFileSync(`${SRC}/features/glossary/glossary.ts`, 'utf8');
const glossJs = ts.transpileModule(glossTs, {
  compilerOptions: { module: 'commonjs', target: 'es2020' },
}).outputText;
const glossModule = { exports: {} };
new Function('exports', 'require', 'module', glossJs)(glossModule.exports, require, glossModule);
const GLOSSARY = glossModule.exports.glossary;
const glossKeys = new Set(Object.keys(GLOSSARY));

const inline = (text) => parseInline(text, glossKeys);

/* ------------------------------------------------------------------ */
/* Chapter blocks                                                     */
/* ------------------------------------------------------------------ */

const SKIP_STRING = /Aria(Label)?$|^legend|^heroAriaLabel$|^quizTitle$/;
const isString = (v) => typeof v === 'string';

function parseBlocks(ch) {
  const blocks = [];
  const takeaways = [];
  for (const [k, v] of Object.entries(ch)) {
    if (/^keyTakeaway\d+$/.test(k) && isString(v)) {
      takeaways.push(inline(v));
      continue;
    }
    if (/^section[A-Z]/.test(k) && isString(v)) {
      blocks.push({ t: 'h', text: v });
      continue;
    }
    if (/^intro\d*$/.test(k) && isString(v)) {
      blocks.push({ t: 'p', marks: inline(v) });
      continue;
    }
    if (/^lab|^quiz_/.test(k)) continue;
    // Figure captions become figure notes.
    if (typeof v === 'object' && v !== null && isString(v.caption)) {
      blocks.push({ t: 'figure', caption: v.caption });
      continue;
    }
    if (typeof v === 'object' && v !== null) continue; // widget/table data
    if (!isString(v)) continue;
    if (SKIP_STRING.test(k)) continue;
    // Long strings are prose; short ones are diagram labels.
    if (v.length >= 55) blocks.push({ t: 'p', marks: inline(v) });
  }
  if (takeaways.length) blocks.push({ t: 'takeaways', items: takeaways });
  return blocks;
}

function parseLab(ch) {
  if (!isString(ch.labGoal)) return null;
  const collect = (re) =>
    Object.keys(ch)
      .filter((k) => re.test(k) && isString(ch[k]))
      .sort()
      .map((k) => inline(ch[k]));
  return {
    goal: inline(ch.labGoal),
    equipment: collect(/^labEquip\d+$/),
    components: collect(/^labComp\d+$/),
    steps: collect(/^labStep\d+$/),
    expected: isString(ch.labExpected) ? inline(ch.labExpected) : null,
    connection: isString(ch.labConnection) ? inline(ch.labConnection) : null,
    trouble: collect(/^labTrouble\d+$/),
  };
}

function parseQuiz(ch) {
  const out = [];
  for (let n = 1; isString(ch[`quiz_q${n}`]); n++) {
    out.push({
      q: inline(ch[`quiz_q${n}`]),
      options: ['a', 'b', 'c', 'd'].map((L) => inline(ch[`quiz_q${n}_${L}`] ?? '')),
      correct: Number(ch[`quiz_q${n}_correct`] ?? 0),
      explanation: inline(ch[`quiz_q${n}_explanation`] ?? ''),
    });
  }
  return out;
}

/* ------------------------------------------------------------------ */
/* Emit                                                               */
/* ------------------------------------------------------------------ */

const HEADER = `/**
 * GENERATED by scripts/convert-course.mjs — do not edit by hand.
 * Content adapted from The Radio Bench (github.com/jemcik/the-radio-bench)
 * © 2026 Yevhen Yemchynskyi, MIT License. See NOTICE.
 */
`;

const parts = ui.parts;
const titles = ui.chapterTitles;
const chapterIds = Object.keys(ui)
  .filter((k) => /^ch\d/.test(k))
  .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const chapters = [];
let quizTotal = 0;
for (const id of chapterIds) {
  const ch = ui[id];
  const num = id.slice(2).replace('_', '-');
  const quiz = parseQuiz(ch);
  quizTotal += quiz.length;
  chapters.push({
    id: num,
    part: Number(num.split('-')[0]),
    title: titles[num] ?? num,
    blocks: parseBlocks(ch),
    lab: parseLab(ch),
    quiz,
  });
}

mkdirSync(`${ROOT}/src/academy/course`, { recursive: true });

const courseOut =
  HEADER +
  `import type { Chapter } from './types';\n\n` +
  `export const PARTS: Record<number, string> = ${JSON.stringify(parts, null, 2)};\n\n` +
  `export const CHAPTERS: Chapter[] = ${JSON.stringify(chapters, null, 1)};\n`;

writeFileSync(`${ROOT}/src/academy/course/course.gen.ts`, courseOut);

const glossOut =
  HEADER +
  `import type { GlossaryMap } from './types';\n\n` +
  `export const GLOSSARY: GlossaryMap = ${JSON.stringify(GLOSSARY, null, 1)};\n`;

writeFileSync(`${ROOT}/src/academy/course/glossary.gen.ts`, glossOut);

console.log(`chapters: ${chapters.length}`);
console.log(`quiz questions: ${quizTotal}`);
console.log(`glossary terms: ${Object.keys(GLOSSARY).length}`);
console.log(`parts: ${Object.values(parts).join(' | ')}`);
