/**
 * Convert the NCVEC amateur radio question pools into typed, code-split modules.
 *
 * Source: the pools are published by the NCVEC Question Pool Committee and
 * released into the public domain. Machine-readable transcriptions come from
 * github.com/russolsen/ham_radio_question_pool (Apache-2.0).
 *
 * Usage: node scripts/convert-pools.mjs
 *   reads  vendor/pools/<pool>.json
 *   writes src/exam/pools/<id>.gen.ts
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SRC = join(ROOT, 'vendor/pools');
const OUT = join(ROOT, 'src/exam/pools');

const POOLS = [
  { id: 'technician', file: 'technician-2026-2030.json', prefix: 'T' },
  { id: 'general', file: 'general-2023-2027.json', prefix: 'G' },
  { id: 'extra', file: 'extra-2024-2028.json', prefix: 'E' },
];

mkdirSync(OUT, { recursive: true });

const esc = (s) => JSON.stringify(s);
let grandTotal = 0;

for (const pool of POOLS) {
  const path = join(SRC, pool.file);
  if (!existsSync(path)) {
    console.error(`MISSING: ${path} — run the download step first.`);
    process.exit(1);
  }
  const raw = JSON.parse(readFileSync(path, 'utf8'));

  const seen = new Set();
  const rows = [];
  for (const r of raw) {
    const id = String(r.id ?? '').trim();
    if (!id) throw new Error(`${pool.file}: record with no id`);
    if (!id.startsWith(pool.prefix)) {
      throw new Error(`${pool.file}: id ${id} does not start with ${pool.prefix}`);
    }
    if (seen.has(id)) throw new Error(`${pool.file}: duplicate id ${id}`);
    seen.add(id);

    const answers = (r.answers ?? []).map((a) => String(a).trim());
    if (answers.length !== 4) {
      throw new Error(`${pool.file}: ${id} has ${answers.length} answers, expected 4`);
    }
    const c = Number(r.correct);
    if (!Number.isInteger(c) || c < 0 || c > 3) {
      throw new Error(`${pool.file}: ${id} has invalid correct index ${r.correct}`);
    }
    // Cross-check the numeric index against the published letter.
    const letter = String(r.correct_letter ?? '').trim().toUpperCase();
    if (letter && 'ABCD'.indexOf(letter) !== c) {
      throw new Error(`${pool.file}: ${id} correct=${c} disagrees with letter ${letter}`);
    }

    const refs = String(r.refs ?? '').trim();
    const fig = String(r.figure ?? '').trim();

    const parts = [
      `id:${esc(id)}`,
      `q:${esc(String(r.question).trim())}`,
      `a:[${answers.map(esc).join(',')}]`,
      `c:${c}`,
    ];
    if (refs) parts.push(`refs:${esc(refs)}`);
    if (fig) parts.push(`fig:${esc(fig)}`);
    rows.push(`{${parts.join(',')}}`);
  }

  // Stable ordering by canonical id keeps diffs readable and reels sequential.
  rows.sort();

  const subs = [...new Set([...seen].map((id) => id.slice(0, 2)))].sort();
  const banner = `/**
 * ${pool.id.toUpperCase()} question pool — ${rows.length} questions, ${subs.length} subelements.
 *
 * GENERATED by scripts/convert-pools.mjs. Do not edit by hand.
 *
 * The questions are the official NCVEC pool, released into the public domain by
 * the NCVEC Question Pool Committee. Transcription via
 * github.com/russolsen/ham_radio_question_pool (Apache-2.0).
 */
import type { PoolQuestion } from '../types';

const QUESTIONS: PoolQuestion[] = [
${rows.join(',\n')}
];

export default QUESTIONS;
`;

  writeFileSync(join(OUT, `${pool.id}.gen.ts`), banner);
  grandTotal += rows.length;
  console.log(
    `${pool.id.padEnd(11)} ${String(rows.length).padStart(4)} questions  ${subs.length} subelements  (${subs.join(' ')})`,
  );
}

console.log(`total       ${String(grandTotal).padStart(4)} questions`);
